# GoReleaser Configuration
# https://goreleaser.com

version: 2

project_name: myapp

before:
  hooks:
    # Tidy dependencies
    - go mod tidy
    # Install templ
    - go install github.com/a-h/templ/cmd/templ@latest
    # Generate templ files
    - templ generate
    # Build CSS for production (CI runs make ci-setup first)
    - cd assets && ./tailwindcss -i input.css -o output.css --minify

builds:
  - id: server
    main: ./cmd/server
    binary: server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: your-username
    name: your-repo
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"
# Docker images (optional)
# dockers:
#   - image_templates:
#       - "ghcr.io/your-username/{{ .ProjectName }}:{{ .Version }}"
#       - "ghcr.io/your-username/{{ .ProjectName }}:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
